apiVersion: v1
kind: Service
metadata:
  name: rag-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rag-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: rag-redis
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: rag-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
