"""
Chat API Router.

Exposes the LangGraph dual-mode agentic RAG workflow via two FastAPI endpoints:

    POST /chat         — Standard JSON request / response.
    POST /chat/stream  — Server-Sent Events (SSE) token stream.

Design decisions:
- All heavy orchestration lives in the workflow; this module is *only* an adapter.
- Session memory is injected into the initial graph state so history reaches the
  answer node without polluting the router, retriever, or SQL engine nodes.
- A unique request_id (UUID4) is attached to every request for distributed tracing.
- Streaming uses asyncio.Queue to bridge the synchronous LangGraph run and the
  async SSE generator.  If the LLM does not support streaming, the workflow falls
  back to ainvoke automatically (see workflow.py answer_node).
- All exceptions are caught at the router level and translated to structured JSON
  error responses with appropriate HTTP status codes.
"""

import asyncio
import json
import time
import uuid
from typing import Any, AsyncGenerator, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field, field_validator

from backend.app.agent.workflow import AgentState, agent_workflow
from backend.app.config import settings
from backend.app.core.logger import logger
from backend.app.memory.memory import memory_store
from backend.app.monitoring.metrics import ERRORS_TOTAL, record_workflow_metrics
from backend.app.core.guardrails import GuardrailException, OutputValidationException
from backend.app.core.logger import logger, session_id_var

# ---------------------------------------------------------------------------
# Router
# ---------------------------------------------------------------------------

router = APIRouter(prefix="/chat", tags=["Chat"])

# ---------------------------------------------------------------------------
# Request / Response Pydantic models
# ---------------------------------------------------------------------------


class ChatRequest(BaseModel):
    """
    Payload for POST /chat and POST /chat/stream.

    Attributes:
        question:   The user's natural-language question. Must be non-empty.
        session_id: Optional identifier used to load / persist conversation
                    history.  A new UUID is generated automatically when omitted.
    """

    question: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's natural-language question (1–2000 characters).",
        examples=["What is the laptop warranty period?"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session identifier for conversation memory. "
        "A new session is created automatically when omitted.",
        examples=["user-abc-123"],
    )

    @field_validator("question")
    @classmethod
    def question_not_blank(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("question must not be blank or whitespace-only.")
        return v.strip()


class ExecutionMetrics(BaseModel):
    """Latency breakdown for each pipeline stage (milliseconds)."""

    router_time_ms: float = 0.0
    retrieval_time_ms: float = 0.0
    sql_generation_time_ms: float = 0.0
    sql_execution_time_ms: float = 0.0
    answer_generation_time_ms: float = 0.0
    total_execution_time_ms: float = 0.0


class ChatResponse(BaseModel):
    """
    Structured response returned by POST /chat.

    All fields are always present; optional data uses empty string / empty list
    defaults so callers never need to handle ``None``.
    """

    request_id: str = Field(description="Unique identifier for this request (UUID4).")
    session_id: str = Field(description="Session identifier used for memory look-up.")
    answer: str = Field(description="Final markdown-formatted answer from the chatbot.")
    route: str = Field(description="Execution path chosen: rag | sql | hybrid.")
    confidence: float = Field(description="Router confidence score (0.0 – 1.0).")
    execution_metrics: ExecutionMetrics = Field(
        description="Per-stage latency breakdown in milliseconds."
    )
    sources: List[str] = Field(
        default_factory=list,
        description="Document chunk citations extracted from the RAG context.",
    )
    sql_query: str = Field(
        default="", description="The SQL query generated by the Text-to-SQL engine."
    )
    sql_result: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="Rows returned by the SQL query execution.",
    )


class ErrorResponse(BaseModel):
    """Structured error envelope returned on 4xx / 5xx responses."""

    request_id: str
    error: str
    detail: str


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _extract_sources(rag_context: str) -> List[str]:
    """
    Parse source citation lines from the RAG context string.

    The workflow formats context as::

        Document chunk:
        <text>
        Source: <citation>

    This helper collects all ``Source:`` lines and de-duplicates them while
    preserving insertion order.
    """
    seen: dict[str, None] = {}
    for line in rag_context.splitlines():
        stripped = line.strip()
        if stripped.startswith("Source:"):
            citation = stripped[len("Source:"):].strip()
            if citation:
                seen[citation] = None
    return list(seen.keys())


def _parse_sql_result(sql_result_raw: Any) -> List[Dict[str, Any]]:
    """
    Attempt to deserialise the SQL result string produced by the workflow.

    The workflow serialises results as a JSON array.  On error or empty result
    an empty list is returned so the API response is always valid.
    """
    if isinstance(sql_result_raw, list):
        return sql_result_raw
    if isinstance(sql_result_raw, dict):
        return [sql_result_raw]
    
    if not isinstance(sql_result_raw, str):
        return []
        
    sql_result_str = sql_result_raw
    if not sql_result_str or sql_result_str.startswith("Error:") or sql_result_str.startswith("Exception:"):
        return []
    try:
        parsed = json.loads(sql_result_str)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, dict):
            return [parsed]
        return []
    except (json.JSONDecodeError, ValueError):
        return []


def _build_initial_state(
    question: str,
    conversation_history: str,
    stream_queue: Optional[asyncio.Queue],
) -> AgentState:
    """Construct the initial AgentState dict fed to the compiled LangGraph graph."""
    return AgentState(
        question=question,
        route="",
        rag_context="",
        sql_query="",
        sql_result="",
        final_answer="",
        confidence=0.0,
        execution_metrics={},
        conversation_history=conversation_history,
        stream_queue=stream_queue,
    )


def _metrics_from_dict(raw: dict) -> ExecutionMetrics:
    """Safely build an ExecutionMetrics model from the raw workflow dict."""
    return ExecutionMetrics(
        router_time_ms=raw.get("router_time_ms", 0.0),
        retrieval_time_ms=raw.get("retrieval_time_ms", 0.0),
        sql_generation_time_ms=raw.get("sql_generation_time_ms", 0.0),
        sql_execution_time_ms=raw.get("sql_execution_time_ms", 0.0),
        answer_generation_time_ms=raw.get("answer_generation_time_ms", 0.0),
        total_execution_time_ms=raw.get("total_execution_time_ms", 0.0),
    )


# ---------------------------------------------------------------------------
# POST /chat — Standard (non-streaming) endpoint
# ---------------------------------------------------------------------------


@router.post(
    "",
    response_model=ChatResponse,
    status_code=status.HTTP_200_OK,
    summary="Send a question to the dual-mode RAG chatbot",
    description=(
        "Accepts a natural-language question and an optional session_id.  "
        "The agent router classifies the query (rag | sql | hybrid), executes "
        "the appropriate retrieval pipeline, and returns a structured JSON response."
    ),
    responses={
        400: {"model": ErrorResponse, "description": "Bad request — blank or invalid question."},
        422: {"description": "Validation error — request body does not match schema."},
        500: {"model": ErrorResponse, "description": "Internal server error — workflow failure."},
    },
)
async def chat(request: ChatRequest) -> ChatResponse:
    """
    Standard chat endpoint.

    Workflow:
    1. Resolve / create session_id.
    2. Load conversation history from memory store.
    3. Build initial LangGraph state.
    4. Invoke the compiled workflow asynchronously.
    5. Persist the new turn (question + answer) to memory.
    6. Return a structured ChatResponse.
    """
    request_id = str(uuid.uuid4())
    wall_start = time.perf_counter()

    # Resolve session
    session_id = request.session_id or str(uuid.uuid4())
    session_id_var.set(session_id)

    logger.info(
        "[Chat API] request_id=%s session_id=%s question='%s'",
        request_id,
        session_id,
        request.question[:120],
    )

    # Load memory
    conversation_history = ""
    if settings.ENABLE_MEMORY:
        try:
            conversation_history = memory_store.get_history(session_id)
        except Exception as mem_exc:
            logger.warning("[Chat API] Memory load failed: %s", mem_exc)

    # Build state and invoke graph
    initial_state = _build_initial_state(
        question=request.question,
        conversation_history=conversation_history,
        stream_queue=None,
    )

    try:
        result: AgentState = await agent_workflow.ainvoke(initial_state)
    except GuardrailException as exc:
        logger.warning("[Chat API] Guardrail violation | request_id=%s | error=%s", request_id, exc)
        ERRORS_TOTAL.labels(component="workflow", error_type=type(exc).__name__).inc()
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(exc),
        )
    except OutputValidationException as exc:
        logger.warning("[Chat API] Output validation violation | request_id=%s | error=%s", request_id, exc)
        ERRORS_TOTAL.labels(component="workflow", error_type=type(exc).__name__).inc()
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        )
    except Exception as exc:
        logger.exception(
            "[Chat API] Workflow error | request_id=%s | error=%s", request_id, exc
        )
        ERRORS_TOTAL.labels(component="workflow", error_type=type(exc).__name__).inc()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(exc),
        )

    # Emit Prometheus workflow metrics
    record_workflow_metrics(
        execution_metrics=result.get("execution_metrics", {}),
        route=result.get("route", "unknown"),
    )

    # Persist turn to memory
    if settings.ENABLE_MEMORY:
        try:
            memory_store.add_message(session_id, "human", request.question)
            memory_store.add_message(session_id, "assistant", result.get("final_answer", ""))
        except Exception as mem_exc:
            logger.warning("[Chat API] Memory save failed: %s", mem_exc)

    wall_ms = (time.perf_counter() - wall_start) * 1000
    logger.info(
        "[Chat API] request_id=%s | route=%s | confidence=%.2f | total_wall_ms=%.1f",
        request_id,
        result.get("route", "unknown"),
        result.get("confidence", 0.0),
        wall_ms,
    )

    return ChatResponse(
        request_id=request_id,
        session_id=session_id,
        answer=result.get("final_answer", ""),
        route=result.get("route", ""),
        confidence=result.get("confidence", 0.0),
        execution_metrics=_metrics_from_dict(result.get("execution_metrics", {})),
        sources=_extract_sources(result.get("rag_context", "")),
        sql_query=result.get("sql_query", ""),
        sql_result=_parse_sql_result(result.get("sql_result", "")),
    )


# ---------------------------------------------------------------------------
# POST /chat/stream — Server-Sent Events streaming endpoint
# ---------------------------------------------------------------------------


async def _sse_event(data: str) -> str:
    """Encode a string as a well-formed SSE ``data:`` line."""
    # Escape embedded newlines so they don't break the SSE framing.
    payload = data.replace("\n", "\\n")
    return f"data: {payload}\n\n"


async def _token_generator(
    question: str,
    session_id: str,
    conversation_history: str,
    request_id: str,
) -> AsyncGenerator[str, None]:
    """
    Run the LangGraph workflow with a stream_queue and yield SSE events.

    The answer_node places token strings into the queue and signals completion
    with a ``None`` sentinel.  A separate asyncio.Task runs the full workflow
    so the queue reader and the graph run concurrently on the same event loop.

    If the LLM or the workflow raises an exception the error is surfaced as a
    JSON-encoded SSE ``error`` event before the stream closes.
    """
    queue: asyncio.Queue[Optional[str]] = asyncio.Queue()

    initial_state = _build_initial_state(
        question=question,
        conversation_history=conversation_history,
        stream_queue=queue,
    )

    # Run the workflow as a background task
    workflow_task: asyncio.Task = asyncio.create_task(
        agent_workflow.ainvoke(initial_state)
    )

    final_result: Optional[AgentState] = None
    full_answer_parts: List[str] = []

    try:
        while True:
            if workflow_task.done():
                if workflow_task.exception():
                    raise workflow_task.exception()
            
            try:
                # Wait for the next token
                token: Optional[str] = await asyncio.wait_for(
                    queue.get(), timeout=1.0
                )
            except asyncio.TimeoutError:
                if workflow_task.done():
                    continue
                # If we've waited longer than LLM_TIMEOUT in total, we could timeout here,
                # but for simplicity and responsiveness we just continue and check workflow_task
                continue

            if token is None:
                # Sentinel: stream complete
                break

            full_answer_parts.append(token)
            yield await _sse_event(json.dumps({"token": token}))

        # Await the workflow task to retrieve full state for metadata
        try:
            final_result = await workflow_task
        except Exception as task_exc:
            logger.error("[Chat Stream] Workflow task error: %s", task_exc)

    except asyncio.CancelledError:
        workflow_task.cancel()
        raise

    except GuardrailException as exc:
        logger.warning("[Chat Stream] Guardrail violation | request_id=%s | error=%s", request_id, exc)
        yield await _sse_event(json.dumps({"error": str(exc), "code": 400}))
        workflow_task.cancel()
        return
    except OutputValidationException as exc:
        logger.warning("[Chat Stream] Output validation violation | request_id=%s | error=%s", request_id, exc)
        yield await _sse_event(json.dumps({"error": str(exc), "code": 422}))
        workflow_task.cancel()
        return
    except Exception as exc:
        logger.exception("[Chat Stream] Generator error | request_id=%s | %s", request_id, exc)
        yield await _sse_event(json.dumps({"error": str(exc), "code": 500}))
        workflow_task.cancel()
        return

    # Emit final metadata event
    if final_result:
        metadata = {
            "done": True,
            "route": final_result.get("route", ""),
            "confidence": final_result.get("confidence", 0.0),
            "session_id": session_id,
            "request_id": request_id,
            "sources": _extract_sources(final_result.get("rag_context", "")),
            "sql_query": final_result.get("sql_query", ""),
            "sql_result": _parse_sql_result(final_result.get("sql_result", "")),
            "execution_metrics": final_result.get("execution_metrics", {}),
        }
        yield await _sse_event(json.dumps(metadata))

        # Persist turn to memory after stream completes
        if settings.ENABLE_MEMORY:
            full_answer = "".join(full_answer_parts)
            try:
                memory_store.add_message(session_id, "human", question)
                memory_store.add_message(session_id, "assistant", full_answer)
            except Exception as mem_exc:
                logger.warning("[Chat Stream] Memory save failed: %s", mem_exc)

    yield "data: [DONE]\n\n"


@router.post(
    "/stream",
    summary="Stream the chatbot response token-by-token via SSE",
    description=(
        "Identical to POST /chat but returns a ``text/event-stream`` response "
        "where each token is emitted as a Server-Sent Event.  A final event "
        "with ``done=true`` carries route, confidence, sources, and metrics. "
        "Falls back to a single-chunk response if the LLM does not support streaming."
    ),
    response_class=StreamingResponse,
    responses={
        200: {"description": "Server-Sent Events stream (text/event-stream)."},
        400: {"model": ErrorResponse, "description": "Bad request."},
        422: {"description": "Validation error."},
        500: {"model": ErrorResponse, "description": "Workflow error."},
    },
)
async def chat_stream(request: ChatRequest) -> StreamingResponse:
    """
    Streaming chat endpoint using Server-Sent Events.

    Clients should consume the ``data:`` lines and parse each JSON payload.
    The stream ends with the literal ``data: [DONE]`` sentinel line.
    """
    request_id = str(uuid.uuid4())
    session_id = request.session_id or str(uuid.uuid4())
    session_id_var.set(session_id)

    logger.info(
        "[Chat Stream] request_id=%s session_id=%s question='%s'",
        request_id,
        session_id,
        request.question[:120],
    )

    # Load memory before entering the generator
    conversation_history = ""
    if settings.ENABLE_MEMORY:
        try:
            conversation_history = memory_store.get_history(session_id)
        except Exception as mem_exc:
            logger.warning("[Chat Stream] Memory load failed: %s", mem_exc)

    return StreamingResponse(
        _token_generator(
            question=request.question,
            session_id=session_id,
            conversation_history=conversation_history,
            request_id=request_id,
        ),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
            "Connection": "keep-alive",
            "X-Request-ID": request_id,
        },
    )
